version: '3.9'
services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  atlas:
    image: arigaio/atlas:0.14.0
    volumes:
      - ./atlas.hcl:/atlas.hcl
      - ./migrations:/migrations
    profiles: ["cli"]
volumes:
  db-data:
    driver: local